# Generated by Django 3.0.1 on 2020-01-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('tweetlink', models.URLField()),
                ('tweetimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
