# Generated by Django 3.0.1 on 2020-01-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagedata_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='tweetimage',
            field=models.URLField(),
        ),
    ]
