# Generated by Django 3.0.1 on 2020-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imagedata_tweet_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='tweetimage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='tweetlink',
            field=models.URLField(null=True),
        ),
    ]
