# Generated by Django 3.0.1 on 2020-01-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200104_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='tweet_image_field',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='tweetimage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='tweetlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
