# Generated by Django 3.0.1 on 2020-01-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200104_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='media_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
